apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iiquugsqe-python 
  janus-idp.io/tekton: iiquugsqe-python
  backstage.io/kubernetes-id: iiquugsqe-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iiquugsqe-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml